# Generated by Django 4.2.4 on 2023-08-18 07:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('invite_code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(regex='[\\dA-Za-z]{6}')])),
                ('invitation_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PhoneNumberApp.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
